OPENAI_API_KEY = "your-openai-api-key"
DATABASE_URL = "postgresql://user:pass@localhost/db"
TWILIO_ACCOUNT_SID = "ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
TWILIO_AUTH_TOKEN = "your-twilio-auth-token"
TWILIO_NUMBER = "+15555555555"
TWILIO_FORWARD_NUMBER = "+15555555555"
SENDGRID_API_KEY = "your-sendgrid-api-key"
FROM_EMAIL = "no-reply@example.com"
BASE_URL = "https://your-app-url.com"
WS_URL = "wss://your-app-url.com/voice/ws"
ELEVENLABS_VOICE_ID = "your-voice-id"
COMPANY_NAME = "Dash Movers"
COMPANY_CITY = "Your City"
