OPENAI_API_KEY = "your-openai-api-key"
DATABASE_URL = "postgresql+psycopg://user:pass@localhost/db"
TWILIO_ACCOUNT_SID = "ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
TWILIO_AUTH_TOKEN = "your-twilio-auth-token"
TWILIO_NUMBER = "+15555555555"
TWILIO_FORWARD_NUMBER = "+15555555555"
AWS_SES_REGION = "us-east-1"
AWS_SES_ACCESS_KEY_ID = "your-aws-access-key-id"
AWS_SES_SECRET_ACCESS_KEY = "your-aws-secret-access-key"
# Optional: provide a configuration set name if you use one
AWS_SES_CONFIGURATION_SET = ""
FROM_EMAIL = "no-reply@example.com"
BASE_URL = "https://your-app-url.com"
WS_URL = "wss://your-app-url.com/voice/ws"
ELEVENLABS_VOICE_ID = "your-voice-id"
COMPANY_NAME = "Dash Movers"
COMPANY_CITY = "Your City"
